In [1]:
import pandas as pd

In [2]:
import yfinance as yf

In [3]:
data = yf.Ticker("AAPL")

In [4]:
data

yfinance.Ticker object <AAPL>

In [5]:
data.info

{'address1': 'One Apple Park Way',
 'city': 'Cupertino',
 'state': 'CA',
 'zip': '95014',
 'country': 'United States',
 'phone': '(408) 996-1010',
 'website': 'https://www.apple.com',
 'industry': 'Consumer Electronics',
 'industryKey': 'consumer-electronics',
 'industryDisp': 'Consumer Electronics',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Apple Inc. designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories worldwide. The company offers iPhone, a line of smartphones; Mac, a line of personal computers; iPad, a line of multi-purpose tablets; and wearables, home, and accessories comprising AirPods, Apple Vision Pro, Apple TV, Apple Watch, Beats products, and HomePod, as well as Apple branded and third-party accessories. It also provides AppleCare support and cloud services; and operates various platforms, including the App Store that allow customers to discover and download applications and digital content, such as books, music, video, games, and podcasts, as well as advertising services include third-party licensing arrangements and its own advertising platforms. In addition, the company offers various subscription-based services, such as Apple Arcade, a game subscription service; Apple Fitness+, a personalized fitness service; Apple Music, which offers users a curated listening experience with on-demand radio stations; Apple News+, a subscription news and magazine service; Apple TV, which offers exclusive original content and live sports; Apple Card, a co-branded credit card; and Apple Pay, a cashless payment service, as well as licenses its intellectual property. The company serves consumers, and small and mid-sized businesses; and the education, enterprise, and government markets. It distributes third-party applications for its products through the App Store. The company also sells its products through its retail and online stores, and direct sales force; and third-party cellular network carriers and resellers. The company was formerly known as Apple Computer, Inc. and changed its name to Apple Inc. in January 2007. Apple Inc. was founded in 1976 and is headquartered in Cupertino, California.',
 'fullTimeEmployees': 166000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Timothy D. Cook',
   'age': 64,
   'title': 'CEO & Director',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'totalPay': 16759518,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Kevan  Parekh',
   'age': 53,
   'title': 'Senior VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2025,
   'totalPay': 4034174,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Sabih  Khan',
   'age': 58,
   'title': 'Senior VP & Chief Operating Officer',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5021905,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Katherine L. Adams',
   'age': 61,
   'title': 'Senior VP, General Counsel & Secretary',
   'yearBorn': 1964,
   'fiscalYear': 2025,
   'totalPay': 5022482,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': "Ms. Deirdre  O'Brien",
   'age': 58,
   'title': 'Senior Vice President of Retail & People',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 5037867,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ben  Borders',
   'age': 44,
   'title': 'Principal Accounting Officer',
   'yearBorn': 1981,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Suhasini  Chandramouli',
   'title': 'Director of Investor Relations',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Kristin Huguet Quayle',
   'title': 'Vice President of Worldwide Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Greg  Joswiak',
   'title': 'Senior Vice President of Worldwide Marketing',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Adrian  Perica',
   'age': 51,
   'title': 'Vice President of Corporate Development',
   'yearBorn': 1974,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 7,
 'boardRisk': 1,
 'compensationRisk': 3,
 'shareHolderRightsRisk': 1,
 'overallRisk': 1,
 'governanceEpochDate': 1768176000,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://investor.apple.com/',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 248.04,
 'open': 251.48,
 'dayLow': 249.8,
 'dayHigh': 256.56,
 'regularMarketPreviousClose': 248.04,
 'regularMarketOpen': 251.48,
 'regularMarketDayLow': 249.8,
 'regularMarketDayHigh': 256.56,
 'dividendRate': 1.04,
 'dividendYield': 0.42,
 'exDividendDate': 1762732800,
 'payoutRatio': 0.1367,
 'fiveYearAvgDividendYield': 0.52,
 'beta': 1.093,
 'trailingPE': 34.191433,
 'forwardPE': 27.930084,
 'volume': 55448748,
 'regularMarketVolume': 55448748,
 'averageVolume': 46402236,
 'averageVolume10days': 49878560,
 'averageDailyVolume10Day': 49878560,
 'bid': 255.25,
 'ask': 255.71,
 'bidSize': 1,
 'askSize': 2,
 'marketCap': 3774028185600,
 'fiftyTwoWeekLow': 169.21,
 'fiftyTwoWeekHigh': 288.62,
 'allTimeHigh': 288.62,
 'allTimeLow': 0.049107,
 'priceToSalesTrailing12Months': 9.068673,
 'fiftyDayAverage': 269.7684,
 'twoHundredDayAverage': 235.02435,
 'trailingAnnualDividendRate': 1.02,
 'trailingAnnualDividendYield': 0.00411224,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 3722806558720,
 'profitMargins': 0.26915002,
 'floatShares': 14750789909,
 'sharesOutstanding': 14697926000,
 'sharesShort': 112732788,
 'sharesShortPriorMonth': 129458559,
 'sharesShortPreviousMonthDate': 1764288000,
 'dateShortInterest': 1767139200,
 'sharesPercentSharesOut': 0.0076,
 'heldPercentInsiders': 0.01702,
 'heldPercentInstitutions': 0.64814,
 'shortRatio': 2.68,
 'shortPercentOfFloat': 0.0076,
 'impliedSharesOutstanding': 14776353000,
 'bookValue': 4.991,
 'priceToBook': 51.174114,
 'lastFiscalYearEnd': 1758931200,
 'nextFiscalYearEnd': 1790467200,
 'mostRecentQuarter': 1758931200,
 'earningsQuarterlyGrowth': 0.864,
 'netIncomeToCommon': 112010002432,
 'trailingEps': 7.47,
 'forwardEps': 9.14462,
 'lastSplitFactor': '4:1',
 'lastSplitDate': 1598832000,
 'enterpriseToRevenue': 8.946,
 'enterpriseToEbitda': 25.719,
 '52WeekChange': 0.041047573,
 'SandP52WeekChange': 0.13974154,
 'lastDividendValue': 0.26,
 'lastDividendDate': 1762732800,
 'quoteType': 'EQUITY',
 'currentPrice': 255.41,
 'targetHighPrice': 350.0,
 'targetLowPrice': 205.0,
 'targetMeanPrice': 287.2949,
 'targetMedianPrice': 300.0,
 'recommendationMean': 2.0,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 41,
 'totalCash': 54697000960,
 'totalCashPerShare': 3.702,
 'ebitda': 144748003328,
 'totalDebt': 112377004032,
 'quickRatio': 0.771,
 'currentRatio': 0.893,
 'totalRevenue': 416161005568,
 'debtToEquity': 152.411,
 'revenuePerShare': 27.84,
 'returnOnAssets': 0.22964,
 'returnOnEquity': 1.7142199,
 'grossProfits': 195201007616,
 'freeCashflow': 78862254080,
 'operatingCashflow': 111482003456,
 'earningsGrowth': 0.912,
 'revenueGrowth': 0.079,
 'grossMargins': 0.46905,
 'ebitdaMargins': 0.34782,
 'operatingMargins': 0.31647,
 'financialCurrency': 'USD',
 'symbol': 'AAPL',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'POSTPOST',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 345479400000,
 'postMarketChangePercent': 0.42672753,
 'postMarketPrice': 256.4999,
 'postMarketChange': 1.0899048,
 'regularMarketChange': 7.37001,
 'regularMarketDayRange': '249.8 - 256.56',
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 46402236,
 'fiftyTwoWeekLowChange': 86.2,
 'fiftyTwoWeekLowChangePercent': 0.5094261,
 'fiftyTwoWeekRange': '169.21 - 288.62',
 'fiftyTwoWeekHighChange': -33.20999,
 'fiftyTwoWeekHighChangePercent': -0.11506476,
 'fiftyTwoWeekChangePercent': 4.1047573,
 'dividendDate': 1762992000,
 'earningsTimestamp': 1769720400,
 'earningsTimestampStart': 1769720400,
 'earningsTimestampEnd': 1769720400,
 'earningsCallTimestampStart': 1769724000,
 'earningsCallTimestampEnd': 1769724000,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 7.47,
 'epsForward': 9.14462,
 'epsCurrentYear': 8.26639,
 'priceEpsCurrentYear': 30.897406,
 'fiftyDayAverageChange': -14.358398,
 'fiftyDayAverageChangePercent': -0.05322491,
 'twoHundredDayAverageChange': 20.38565,
 'twoHundredDayAverageChangePercent': 0.08673846,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'averageAnalystRating': '2.0 - Buy',
 'cryptoTradeable': False,
 'corporateActions': [],
 'postMarketTime': 1769475592,
 'regularMarketTime': 1769461201,
 'exchange': 'NMS',
 'messageBoardId': 'finmb_24937',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EST',
 'gmtOffSetMilliseconds': -18000000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 2.9713,
 'regularMarketPrice': 255.41,
 'shortName': 'Apple Inc.',
 'longName': 'Apple Inc.',
 'displayName': 'Apple',
 'trailingPegRatio': 2.5101}

In [6]:
data.calendar

{'Dividend Date': datetime.date(2025, 11, 12),
 'Ex-Dividend Date': datetime.date(2025, 11, 9),
 'Earnings Date': [datetime.date(2026, 1, 29)],
 'Earnings High': 2.8,
 'Earnings Low': 2.45,
 'Earnings Average': 2.67195,
 'Revenue High': 142460000000,
 'Revenue Low': 136656000000,
 'Revenue Average': 138484726120}

In [7]:
yf.download(["AAPL"], start="2023-01-01", end="2026-01-01")

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2023-01-03  123.211220  128.954569  122.324594  128.343788  112117500
2023-01-04  124.482025  126.747845  123.221050  125.004147   89113600
2023-01-05  123.161949  125.871079  122.905819  125.240591   80962700
2023-01-06  127.693565  128.353606  123.033867  124.137225   87754700
2023-01-09  128.215729  131.427289  127.959598  128.530980   70790800
...                ...         ...         ...         ...        ...
2025-12-24  273.809998  275.429993  272.200012  272.339996   17910600
2025-12-26  273.399994  275.369995  272.859985  274.160004   21521800
2025-12-29  273.760010  274.359985  272.350006  272.690002   23715200
2025-12-30  273.079987  274.079987  272.279999  272.809998   22139600
2025-12-31  271.859985  273.679993  271.750000  273.059998   27293600

[752 rows x 5 columns]

In [8]:
df = yf.download(["AAPL"], start="2023-01-01", end="2026-01-01")

[*********************100%***********************]  1 of 1 completed

In [9]:
df

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2023-01-03  123.211220  128.954569  122.324594  128.343788  112117500
2023-01-04  124.482025  126.747845  123.221050  125.004147   89113600
2023-01-05  123.161949  125.871079  122.905819  125.240591   80962700
2023-01-06  127.693565  128.353606  123.033867  124.137225   87754700
2023-01-09  128.215729  131.427289  127.959598  128.530980   70790800
...                ...         ...         ...         ...        ...
2025-12-24  273.809998  275.429993  272.200012  272.339996   17910600
2025-12-26  273.399994  275.369995  272.859985  274.160004   21521800
2025-12-29  273.760010  274.359985  272.350006  272.690002   23715200
2025-12-30  273.079987  274.079987  272.279999  272.809998   22139600
2025-12-31  271.859985  273.679993  271.750000  273.059998   27293600

[752 rows x 5 columns]

In [10]:
df_t = df.T

In [11]:
df_t

,Date,2023-01-03,2023-01-04,2023-01-05,2023-01-06,2023-01-09,2023-01-10,2023-01-11,2023-01-12,2023-01-13,2023-01-17,...,2025-12-17,2025-12-18,2025-12-19,2025-12-22,2025-12-23,2025-12-24,2025-12-26,2025-12-29,2025-12-30,2025-12-31
Price,Ticker,,,,,,,,,,,,,,,,,,,,,
Close,AAPL,1.232112e+02,1.244820e+02,1.231619e+02,1.276936e+02,1.282157e+02,1.287871e+02,1.315061e+02,1.314273e+02,1.327572e+02,1.339196e+02,...,2.718400e+02,2.721900e+02,2.736700e+02,2.709700e+02,2.723600e+02,2.738100e+02,2.734000e+02,2.737600e+02,2.730800e+02,2.718600e+02
High,AAPL,1.289546e+02,1.267478e+02,1.258711e+02,1.283536e+02,1.314273e+02,1.293092e+02,1.315258e+02,1.322646e+02,1.329148e+02,1.352496e+02,...,2.761600e+02,2.736300e+02,2.746000e+02,2.738800e+02,2.725000e+02,2.754300e+02,2.753700e+02,2.743600e+02,2.740800e+02,2.736800e+02
Low,AAPL,1.223246e+02,1.232210e+02,1.229058e+02,1.230339e+02,1.279596e+02,1.262159e+02,1.285211e+02,1.294866e+02,1.297033e+02,1.321366e+02,...,2.716400e+02,2.669500e+02,2.699000e+02,2.705100e+02,2.695600e+02,2.722000e+02,2.728600e+02,2.723500e+02,2.722800e+02,2.717500e+02
Open,AAPL,1.283438e+02,1.250041e+02,1.252406e+02,1.241372e+02,1.285310e+02,1.283241e+02,1.292994e+02,1.318903e+02,1.300678e+02,1.328261e+02,...,2.750100e+02,2.736100e+02,2.721500e+02,2.728600e+02,2.708400e+02,2.723400e+02,2.741600e+02,2.726900e+02,2.728100e+02,2.730600e+02
Volume,AAPL,1.121175e+08,8.911360e+07,8.096270e+07,8.775470e+07,7.079080e+07,6.389620e+07,6.945890e+07,7.137960e+07,5.780970e+07,6.364660e+07,...,5.013870e+07,5.163070e+07,1.446320e+08,3.657180e+07,2.964200e+07,1.791060e+07,2.152180e+07,2.371520e+07,2.213960e+07,2.729360e+07

In [12]:
df

Price            Close        High         Low        Open     Volume
Ticker            AAPL        AAPL        AAPL        AAPL       AAPL
Date
2023-01-03  123.211220  128.954569  122.324594  128.343788  112117500
2023-01-04  124.482025  126.747845  123.221050  125.004147   89113600
2023-01-05  123.161949  125.871079  122.905819  125.240591   80962700
2023-01-06  127.693565  128.353606  123.033867  124.137225   87754700
2023-01-09  128.215729  131.427289  127.959598  128.530980   70790800
...                ...         ...         ...         ...        ...
2025-12-24  273.809998  275.429993  272.200012  272.339996   17910600
2025-12-26  273.399994  275.369995  272.859985  274.160004   21521800
2025-12-29  273.760010  274.359985  272.350006  272.690002   23715200
2025-12-30  273.079987  274.079987  272.279999  272.809998   22139600
2025-12-31  271.859985  273.679993  271.750000  273.059998   27293600

[752 rows x 5 columns]

In [13]:
df.columns = df.columns.droplevel(1)

In [14]:
df

Price            Close        High         Low        Open     Volume
Date
2023-01-03  123.211220  128.954569  122.324594  128.343788  112117500
2023-01-04  124.482025  126.747845  123.221050  125.004147   89113600
2023-01-05  123.161949  125.871079  122.905819  125.240591   80962700
2023-01-06  127.693565  128.353606  123.033867  124.137225   87754700
2023-01-09  128.215729  131.427289  127.959598  128.530980   70790800
...                ...         ...         ...         ...        ...
2025-12-24  273.809998  275.429993  272.200012  272.339996   17910600
2025-12-26  273.399994  275.369995  272.859985  274.160004   21521800
2025-12-29  273.760010  274.359985  272.350006  272.690002   23715200
2025-12-30  273.079987  274.079987  272.279999  272.809998   22139600
2025-12-31  271.859985  273.679993  271.750000  273.059998   27293600

[752 rows x 5 columns]

In [15]:
df = df.reset_index()

In [16]:
df

Price       Date       Close        High         Low        Open     Volume
0     2023-01-03  123.211220  128.954569  122.324594  128.343788  112117500
1     2023-01-04  124.482025  126.747845  123.221050  125.004147   89113600
2     2023-01-05  123.161949  125.871079  122.905819  125.240591   80962700
3     2023-01-06  127.693565  128.353606  123.033867  124.137225   87754700
4     2023-01-09  128.215729  131.427289  127.959598  128.530980   70790800
..           ...         ...         ...         ...         ...        ...
747   2025-12-24  273.809998  275.429993  272.200012  272.339996   17910600
748   2025-12-26  273.399994  275.369995  272.859985  274.160004   21521800
749   2025-12-29  273.760010  274.359985  272.350006  272.690002   23715200
750   2025-12-30  273.079987  274.079987  272.279999  272.809998   22139600
751   2025-12-31  271.859985  273.679993  271.750000  273.059998   27293600

[752 rows x 6 columns]

In [17]:
df['name'] = "AAPL"

In [18]:
df

Price,Date,Close,High,Low,Open,Volume,name
0,2023-01-03,123.211220,128.954569,122.324594,128.343788,112117500,AAPL
1,2023-01-04,124.482025,126.747845,123.221050,125.004147,89113600,AAPL
2,2023-01-05,123.161949,125.871079,122.905819,125.240591,80962700,AAPL
3,2023-01-06,127.693565,128.353606,123.033867,124.137225,87754700,AAPL
4,2023-01-09,128.215729,131.427289,127.959598,128.530980,70790800,AAPL
...,...,...,...,...,...,...,...
747,2025-12-24,273.809998,275.429993,272.200012,272.339996,17910600,AAPL
748,2025-12-26,273.399994,275.369995,272.859985,274.160004,21521800,AAPL
749,2025-12-29,273.760010,274.359985,272.350006,272.690002,23715200,AAPL
750,2025-12-30,273.079987,274.079987,272.279999,272.809998,22139600,AAPL
751,2025-12-31,271.859985,273.679993,271.750000,273.059998,27293600,AAPL

In [19]:
df = df[["Date", "Open", "High", "Low", "Close", "Volume", "name"]]
df.head()

Price,Date,Open,High,Low,Close,Volume,name
0,2023-01-03,128.343788,128.954569,122.324594,123.211220,112117500,AAPL
1,2023-01-04,125.004147,126.747845,123.221050,124.482025,89113600,AAPL
2,2023-01-05,125.240591,125.871079,122.905819,123.161949,80962700,AAPL
3,2023-01-06,124.137225,128.353606,123.033867,127.693565,87754700,AAPL
4,2023-01-09,128.530980,131.427289,127.959598,128.215729,70790800,AAPL

In [20]:
df.to_csv('output.csv')

In [21]:
data = pd.read_csv('data/sp500_companies.csv')
data

,Exchange,Symbol,Shortname,Longname,Sector,Industry,Currentprice,Marketcap,Ebitda,Revenuegrowth,City,State,Country,Fulltimeemployees,Longbusinesssummary,Weight
0,NMS,AAPL,Apple Inc.,Apple Inc.,Technology,Consumer Electronics,254.49,3846819807232,1.346610e+11,0.061,Cupertino,CA,United States,164000.0,"Apple Inc. designs, manufactures, and markets ...",0.069209
1,NMS,NVDA,NVIDIA Corporation,NVIDIA Corporation,Technology,Semiconductors,134.70,3298803056640,6.118400e+10,1.224,Santa Clara,CA,United States,29600.0,NVIDIA Corporation provides graphics and compu...,0.059350
2,NMS,MSFT,Microsoft Corporation,Microsoft Corporation,Technology,Software - Infrastructure,436.60,3246068596736,1.365520e+11,0.160,Redmond,WA,United States,228000.0,Microsoft Corporation develops and supports so...,0.058401
3,NMS,AMZN,"Amazon.com, Inc.","Amazon.com, Inc.",Consumer Cyclical,Internet Retail,224.92,2365033807872,1.115830e+11,0.110,Seattle,WA,United States,1551000.0,"Amazon.com, Inc. engages in the retail sale of...",0.042550
4,NMS,GOOGL,Alphabet Inc.,Alphabet Inc.,Communication Services,Internet Content & Information,191.41,2351625142272,1.234700e+11,0.151,Mountain View,CA,United States,181269.0,Alphabet Inc. offers various products and plat...,0.042309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
497,NMS,CZR,"Caesars Entertainment, Inc.","Caesars Entertainment, Inc.",Consumer Cyclical,Resorts & Casinos,32.82,6973593600,3.668000e+09,-0.040,Reno,NV,United States,51000.0,"Caesars Entertainment, Inc. operates as a gami...",0.000125
498,NYQ,BWA,BorgWarner Inc.,BorgWarner Inc.,Consumer Cyclical,Auto Parts,31.88,6972155904,1.882000e+09,-0.048,Auburn Hills,MI,United States,39900.0,"BorgWarner Inc., together with its subsidiarie...",0.000125
499,NMS,QRVO,"Qorvo, Inc.","Qorvo, Inc.",Technology,Semiconductors,70.85,6697217024,6.731300e+08,-0.052,Greensboro,NC,United States,8700.0,"Qorvo, Inc. engages in development and commerc...",0.000120
500,NYQ,FMC,FMC Corporation,FMC Corporation,Basic Materials,Agricultural Inputs,50.15,6260525568,7.033000e+08,0.085,Philadelphia,PA,United States,5800.0,"FMC Corporation, an agricultural sciences comp...",0.000113
501,NYQ,AMTM,"Amentum Holdings, Inc.","Amentum Holdings, Inc.",Industrials,Specialty Business Services,19.17,4664099328,4.330000e+08,-0.031,Chantilly,VA,United States,NaN,"Amentum Holdings, Inc. provides engineering an...",0.000084

In [22]:
data['Symbol']

0       AAPL
1       NVDA
2       MSFT
3       AMZN
4      GOOGL
       ...
497      CZR
498      BWA
499     QRVO
500      FMC
501     AMTM
Name: Symbol, Length: 502, dtype: object

In [25]:
list(data['Symbol'])

['AAPL',
 'NVDA',
 'MSFT',
 'AMZN',
 'GOOGL',
 'GOOG',
 'META',
 'TSLA',
 'AVGO',
 'BRK-B',
 'WMT',
 'LLY',
 'JPM',
 'V',
 'MA',
 'ORCL',
 'XOM',
 'UNH',
 'COST',
 'PG',
 'HD',
 'NFLX',
 'JNJ',
 'BAC',
 'CRM',
 'ABBV',
 'KO',
 'TMUS',
 'CVX',
 'MRK',
 'WFC',
 'CSCO',
 'ACN',
 'NOW',
 'AXP',
 'MCD',
 'PEP',
 'BX',
 'IBM',
 'DIS',
 'LIN',
 'TMO',
 'MS',
 'ABT',
 'ADBE',
 'AMD',
 'PM',
 'ISRG',
 'PLTR',
 'GE',
 'INTU',
 'GS',
 'CAT',
 'TXN',
 'QCOM',
 'VZ',
 'BKNG',
 'DHR',
 'T',
 'BLK',
 'RTX',
 'SPGI',
 'PFE',
 'HON',
 'NEE',
 'CMCSA',
 'ANET',
 'AMGN',
 'PGR',
 'LOW',
 'SYK',
 'UNP',
 'TJX',
 'KKR',
 'SCHW',
 'ETN',
 'AMAT',
 'BA',
 'BSX',
 'C',
 'UBER',
 'COP',
 'PANW',
 'ADP',
 'DE',
 'FI',
 'BMY',
 'LMT',
 'GILD',
 'NKE',
 'CB',
 'UPS',
 'ADI',
 'MMC',
 'MDT',
 'VRTX',
 'MU',
 'SBUX',
 'PLD',
 'GEV',
 'LRCX',
 'MO',
 'SO',
 'EQIX',
 'CRWD',
 'PYPL',
 'SHW',
 'ICE',
 'CME',
 'AMT',
 'APH',
 'ELV',
 'TT',
 'MCO',
 'CMG',
 'INTC',
 'KLAC',
 'ABNB',
 'DUK',
 'PH',
 'CDNS',
 'WM',
 'DELL',
 'MDLZ',
 'MAR',
 'MSI',
 'WELL',
 'AON',
 'REGN',
 'CI',
 'HCA',
 'PNC',
 'ITW',
 'SNPS',
 'CTAS',
 'CL',
 'USB',
 'FTNT',
 'ZTS',
 'MCK',
 'GD',
 'TDG',
 'CEG',
 'AJG',
 'EMR',
 'MMM',
 'ORLY',
 'NOC',
 'COF',
 'ECL',
 'EOG',
 'FDX',
 'BDX',
 'APD',
 'WMB',
 'SPG',
 'ADSK',
 'RCL',
 'RSG',
 'CARR',
 'CSX',
 'HLT',
 'DLR',
 'TGT',
 'KMI',
 'OKE',
 'TFC',
 'AFL',
 'GM',
 'BK',
 'ROP',
 'MET',
 'CPRT',
 'FCX',
 'CVS',
 'PCAR',
 'SRE',
 'AZO',
 'TRV',
 'NXPI',
 'JCI',
 'GWW',
 'NSC',
 'PSA',
 'SLB',
 'AMP',
 'ALL',
 'FICO',
 'MNST',
 'PAYX',
 'CHTR',
 'AEP',
 'ROST',
 'PWR',
 'CMI',
 'AXON',
 'VST',
 'URI',
 'MSCI',
 'LULU',
 'O',
 'PSX',
 'AIG',
 'FANG',
 'D',
 'HWM',
 'DHI',
 'KR',
 'NDAQ',
 'OXY',
 'EW',
 'COR',
 'KDP',
 'FIS',
 'KMB',
 'NEM',
 'DFS',
 'PCG',
 'TEL',
 'MPC',
 'FAST',
 'AME',
 'PEG',
 'PRU',
 'KVUE',
 'STZ',
 'GLW',
 'LHX',
 'GRMN',
 'BKR',
 'CBRE',
 'CTVA',
 'HES',
 'CCI',
 'DAL',
 'CTSH',
 'F',
 'VRSK',
 'EA',
 'ODFL',
 'XEL',
 'TRGP',
 'A',
 'IT',
 'LVS',
 'SYY',
 'VLO',
 'OTIS',
 'LEN',
 'EXC',
 'IR',
 'YUM',
 'KHC',
 'GEHC',
 'IQV',
 'GIS',
 'CCL',
 'RMD',
 'VMC',
 'HSY',
 'ACGL',
 'IDXX',
 'WAB',
 'ROK',
 'MLM',
 'EXR',
 'DD',
 'ETR',
 'DECK',
 'EFX',
 'UAL',
 'WTW',
 'TTWO',
 'HIG',
 'RJF',
 'AVB',
 'MTB',
 'DXCM',
 'ED',
 'EBAY',
 'HPQ',
 'IRM',
 'EIX',
 'LYV',
 'VICI',
 'CNC',
 'WEC',
 'MCHP',
 'HUM',
 'ANSS',
 'BRO',
 'CSGP',
 'MPWR',
 'GDDY',
 'TSCO',
 'STT',
 'CAH',
 'GPN',
 'FITB',
 'XYL',
 'HPE',
 'KEYS',
 'DOW',
 'EQR',
 'ON',
 'PPG',
 'K',
 'SW',
 'NUE',
 'EL',
 'BR',
 'WBD',
 'TPL',
 'CHD',
 'MTD',
 'DOV',
 'TYL',
 'FTV',
 'TROW',
 'VLTO',
 'EQT',
 'SYF',
 'NVR',
 'DTE',
 'VTR',
 'AWK',
 'ADM',
 'NTAP',
 'WST',
 'CPAY',
 'PPL',
 'LYB',
 'AEE',
 'EXPE',
 'HBAN',
 'CDW',
 'FE',
 'HUBB',
 'HAL',
 'ROL',
 'PHM',
 'CINF',
 'PTC',
 'WRB',
 'DRI',
 'FOXA',
 'FOX',
 'IFF',
 'SBAC',
 'WAT',
 'ERIE',
 'TDY',
 'ATO',
 'RF',
 'BIIB',
 'ZBH',
 'CNP',
 'MKC',
 'ES',
 'WDC',
 'TSN',
 'TER',
 'STE',
 'PKG',
 'CLX',
 'NTRS',
 'ZBRA',
 'DVN',
 'CBOE',
 'WY',
 'LUV',
 'ULTA',
 'CMS',
 'INVH',
 'FSLR',
 'BF-B',
 'LDOS',
 'CFG',
 'LH',
 'VRSN',
 'IP',
 'ESS',
 'PODD',
 'COO',
 'SMCI',
 'STX',
 'MAA',
 'FDS',
 'NRG',
 'BBY',
 'SNA',
 'L',
 'PFG',
 'STLD',
 'TRMB',
 'OMC',
 'CTRA',
 'HRL',
 'ARE',
 'BLDR',
 'JBHT',
 'GEN',
 'DGX',
 'KEY',
 'NI',
 'MOH',
 'PNR',
 'J',
 'DG',
 'BALL',
 'NWS',
 'NWSA',
 'UDR',
 'HOLX',
 'JBL',
 'GPC',
 'IEX',
 'MAS',
 'KIM',
 'ALGN',
 'DLTR',
 'EXPD',
 'EG',
 'MRNA',
 'LNT',
 'AVY',
 'BAX',
 'TPR',
 'VTRS',
 'CF',
 'FFIV',
 'DPZ',
 'AKAM',
 'RL',
 'TXT',
 'SWKS',
 'EVRG',
 'EPAM',
 'DOC',
 'APTV',
 'RVTY',
 'AMCR',
 'REG',
 'POOL',
 'INCY',
 'BXP',
 'KMX',
 'CAG',
 'HST',
 'JKHY',
 'SWK',
 'DVA',
 'CPB',
 'CHRW',
 'JNPR',
 'CPT',
 'TAP',
 'NDSN',
 'PAYC',
 'UHS',
 'NCLH',
 'DAY',
 'SJM',
 'TECH',
 'SOLV',
 'ALLE',
 'BG',
 'AIZ',
 'IPG',
 'BEN',
 'EMN',
 'ALB',
 'MGM',
 'AOS',
 'WYNN',
 'PNW',
 'ENPH',
 'LKQ',
 'FRT',
 'CRL',
 'GNRC',
 'AES',
 'GL',
 'LW',
 'HSIC',
 'MKTX',
 'MTCH',
 'TFX',
 'WBA',
 'HAS',
 'IVZ',
 'APA',
 'MOS',
 'PARA',
 'MHK',
 'CE',
 'HII',
 'CZR',
 'BWA',
 'QRVO',
 'FMC',
 'AMTM']

In [26]:
ll = list(data['Symbol'])

In [27]:
ll

['AAPL',
 'NVDA',
 'MSFT',
 'AMZN',
 'GOOGL',
 'GOOG',
 'META',
 'TSLA',
 'AVGO',
 'BRK-B',
 'WMT',
 'LLY',
 'JPM',
 'V',
 'MA',
 'ORCL',
 'XOM',
 'UNH',
 'COST',
 'PG',
 'HD',
 'NFLX',
 'JNJ',
 'BAC',
 'CRM',
 'ABBV',
 'KO',
 'TMUS',
 'CVX',
 'MRK',
 'WFC',
 'CSCO',
 'ACN',
 'NOW',
 'AXP',
 'MCD',
 'PEP',
 'BX',
 'IBM',
 'DIS',
 'LIN',
 'TMO',
 'MS',
 'ABT',
 'ADBE',
 'AMD',
 'PM',
 'ISRG',
 'PLTR',
 'GE',
 'INTU',
 'GS',
 'CAT',
 'TXN',
 'QCOM',
 'VZ',
 'BKNG',
 'DHR',
 'T',
 'BLK',
 'RTX',
 'SPGI',
 'PFE',
 'HON',
 'NEE',
 'CMCSA',
 'ANET',
 'AMGN',
 'PGR',
 'LOW',
 'SYK',
 'UNP',
 'TJX',
 'KKR',
 'SCHW',
 'ETN',
 'AMAT',
 'BA',
 'BSX',
 'C',
 'UBER',
 'COP',
 'PANW',
 'ADP',
 'DE',
 'FI',
 'BMY',
 'LMT',
 'GILD',
 'NKE',
 'CB',
 'UPS',
 'ADI',
 'MMC',
 'MDT',
 'VRTX',
 'MU',
 'SBUX',
 'PLD',
 'GEV',
 'LRCX',
 'MO',
 'SO',
 'EQIX',
 'CRWD',
 'PYPL',
 'SHW',
 'ICE',
 'CME',
 'AMT',
 'APH',
 'ELV',
 'TT',
 'MCO',
 'CMG',
 'INTC',
 'KLAC',
 'ABNB',
 'DUK',
 'PH',
 'CDNS',
 'WM',
 'DELL',
 'MDLZ',
 'MAR',
 'MSI',
 'WELL',
 'AON',
 'REGN',
 'CI',
 'HCA',
 'PNC',
 'ITW',
 'SNPS',
 'CTAS',
 'CL',
 'USB',
 'FTNT',
 'ZTS',
 'MCK',
 'GD',
 'TDG',
 'CEG',
 'AJG',
 'EMR',
 'MMM',
 'ORLY',
 'NOC',
 'COF',
 'ECL',
 'EOG',
 'FDX',
 'BDX',
 'APD',
 'WMB',
 'SPG',
 'ADSK',
 'RCL',
 'RSG',
 'CARR',
 'CSX',
 'HLT',
 'DLR',
 'TGT',
 'KMI',
 'OKE',
 'TFC',
 'AFL',
 'GM',
 'BK',
 'ROP',
 'MET',
 'CPRT',
 'FCX',
 'CVS',
 'PCAR',
 'SRE',
 'AZO',
 'TRV',
 'NXPI',
 'JCI',
 'GWW',
 'NSC',
 'PSA',
 'SLB',
 'AMP',
 'ALL',
 'FICO',
 'MNST',
 'PAYX',
 'CHTR',
 'AEP',
 'ROST',
 'PWR',
 'CMI',
 'AXON',
 'VST',
 'URI',
 'MSCI',
 'LULU',
 'O',
 'PSX',
 'AIG',
 'FANG',
 'D',
 'HWM',
 'DHI',
 'KR',
 'NDAQ',
 'OXY',
 'EW',
 'COR',
 'KDP',
 'FIS',
 'KMB',
 'NEM',
 'DFS',
 'PCG',
 'TEL',
 'MPC',
 'FAST',
 'AME',
 'PEG',
 'PRU',
 'KVUE',
 'STZ',
 'GLW',
 'LHX',
 'GRMN',
 'BKR',
 'CBRE',
 'CTVA',
 'HES',
 'CCI',
 'DAL',
 'CTSH',
 'F',
 'VRSK',
 'EA',
 'ODFL',
 'XEL',
 'TRGP',
 'A',
 'IT',
 'LVS',
 'SYY',
 'VLO',
 'OTIS',
 'LEN',
 'EXC',
 'IR',
 'YUM',
 'KHC',
 'GEHC',
 'IQV',
 'GIS',
 'CCL',
 'RMD',
 'VMC',
 'HSY',
 'ACGL',
 'IDXX',
 'WAB',
 'ROK',
 'MLM',
 'EXR',
 'DD',
 'ETR',
 'DECK',
 'EFX',
 'UAL',
 'WTW',
 'TTWO',
 'HIG',
 'RJF',
 'AVB',
 'MTB',
 'DXCM',
 'ED',
 'EBAY',
 'HPQ',
 'IRM',
 'EIX',
 'LYV',
 'VICI',
 'CNC',
 'WEC',
 'MCHP',
 'HUM',
 'ANSS',
 'BRO',
 'CSGP',
 'MPWR',
 'GDDY',
 'TSCO',
 'STT',
 'CAH',
 'GPN',
 'FITB',
 'XYL',
 'HPE',
 'KEYS',
 'DOW',
 'EQR',
 'ON',
 'PPG',
 'K',
 'SW',
 'NUE',
 'EL',
 'BR',
 'WBD',
 'TPL',
 'CHD',
 'MTD',
 'DOV',
 'TYL',
 'FTV',
 'TROW',
 'VLTO',
 'EQT',
 'SYF',
 'NVR',
 'DTE',
 'VTR',
 'AWK',
 'ADM',
 'NTAP',
 'WST',
 'CPAY',
 'PPL',
 'LYB',
 'AEE',
 'EXPE',
 'HBAN',
 'CDW',
 'FE',
 'HUBB',
 'HAL',
 'ROL',
 'PHM',
 'CINF',
 'PTC',
 'WRB',
 'DRI',
 'FOXA',
 'FOX',
 'IFF',
 'SBAC',
 'WAT',
 'ERIE',
 'TDY',
 'ATO',
 'RF',
 'BIIB',
 'ZBH',
 'CNP',
 'MKC',
 'ES',
 'WDC',
 'TSN',
 'TER',
 'STE',
 'PKG',
 'CLX',
 'NTRS',
 'ZBRA',
 'DVN',
 'CBOE',
 'WY',
 'LUV',
 'ULTA',
 'CMS',
 'INVH',
 'FSLR',
 'BF-B',
 'LDOS',
 'CFG',
 'LH',
 'VRSN',
 'IP',
 'ESS',
 'PODD',
 'COO',
 'SMCI',
 'STX',
 'MAA',
 'FDS',
 'NRG',
 'BBY',
 'SNA',
 'L',
 'PFG',
 'STLD',
 'TRMB',
 'OMC',
 'CTRA',
 'HRL',
 'ARE',
 'BLDR',
 'JBHT',
 'GEN',
 'DGX',
 'KEY',
 'NI',
 'MOH',
 'PNR',
 'J',
 'DG',
 'BALL',
 'NWS',
 'NWSA',
 'UDR',
 'HOLX',
 'JBL',
 'GPC',
 'IEX',
 'MAS',
 'KIM',
 'ALGN',
 'DLTR',
 'EXPD',
 'EG',
 'MRNA',
 'LNT',
 'AVY',
 'BAX',
 'TPR',
 'VTRS',
 'CF',
 'FFIV',
 'DPZ',
 'AKAM',
 'RL',
 'TXT',
 'SWKS',
 'EVRG',
 'EPAM',
 'DOC',
 'APTV',
 'RVTY',
 'AMCR',
 'REG',
 'POOL',
 'INCY',
 'BXP',
 'KMX',
 'CAG',
 'HST',
 'JKHY',
 'SWK',
 'DVA',
 'CPB',
 'CHRW',
 'JNPR',
 'CPT',
 'TAP',
 'NDSN',
 'PAYC',
 'UHS',
 'NCLH',
 'DAY',
 'SJM',
 'TECH',
 'SOLV',
 'ALLE',
 'BG',
 'AIZ',
 'IPG',
 'BEN',
 'EMN',
 'ALB',
 'MGM',
 'AOS',
 'WYNN',
 'PNW',
 'ENPH',
 'LKQ',
 'FRT',
 'CRL',
 'GNRC',
 'AES',
 'GL',
 'LW',
 'HSIC',
 'MKTX',
 'MTCH',
 'TFX',
 'WBA',
 'HAS',
 'IVZ',
 'APA',
 'MOS',
 'PARA',
 'MHK',
 'CE',
 'HII',
 'CZR',
 'BWA',
 'QRVO',
 'FMC',
 'AMTM']

In [28]:
def extract_data(symbol):
    df = yf.download(symbol, start="2023-01-01", end="2026-01-01")
    df.columns = df.columns.droplevel(1)
    df = df.reset_index()
    df['name'] = symbol
    return df

In [30]:
all_symbol = []
for ele in ll:
    data = extract_data(ele)
    all_symbol.append(data)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: FI"}}}
$FI: possibly delisted; no timezone found
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['FI']: possibly delisted; no timezone found
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
$DFS: possibly delisted; no timezone found
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['DFS']: possibly delisted; no timezone found
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
$HES: possibly delisted; no timezone found
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['HES']: possibly delisted; no timezone found
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [31]:
final_df = pd.concat(all_symbol, ignore_index=True)

In [32]:
final_df.to_csv("final.csv")

In [33]:
final_df.shape

(370880, 8)

In [34]:
final_df.head()

Price,Date,Close,High,Low,Open,Volume,name,Adj Close
0,2023-01-03,123.211220,128.954569,122.324594,128.343788,112117500.0,AAPL,NaN
1,2023-01-04,124.482025,126.747845,123.221050,125.004147,89113600.0,AAPL,NaN
2,2023-01-05,123.161949,125.871079,122.905819,125.240591,80962700.0,AAPL,NaN
3,2023-01-06,127.693565,128.353606,123.033867,124.137225,87754700.0,AAPL,NaN
4,2023-01-09,128.215729,131.427289,127.959598,128.530980,70790800.0,AAPL,NaN